### ISSUE TITLE
Download chapter separately 

### ISSUE THREAD

**Issue by logan17111** [ErisLoona/Manga-Library-Manager#1]
As title say
I did a test on Blue Box manga, the result is one .cbz file containing ~3k pages instead of more logic 150 .cbz files

**Comment by ErisLoona** [comment]
Heyo! This is intended, as it says in the feature list the program creates *one* large file, as a complete manga to be read, kept and transferred around in one go.  

Personally I never understood why someone would want the chapters separately, could you please explain that?

**Comment by logan17111** [comment]
As for my personal opinion, I prefer this way because I have always done thing like this so

Also it feels weird to have manga being thousands and thousands pages long, I would personally have hard time tracking where I am if I take a pause.

Maybe doing having possibility to download tome per tome or fuse a number of chapters automatically for manga who aren't serialized (if blue box wasn't, I could for example fuse every 12 chapters and the result would be 12 "full" .cbz and a 13th with a couple of pages.

Overall, even in this state the soft does the job very well (even had the chance to already use "check new chapter") everything's good !

**Comment by ErisLoona** [comment]
Hmm this is a more complex matter of perspective. Thank you for explaining!  

I mostly use `.epub`, specifically the moon+ reader on Android. After finishing an Ongoing manga I delete it while waiting for updates, and once a few chapters are out I "update" it and put it back on my tablet to continue reading.  
Here's the thing, moon+ picks up the manga exactly from where I left off, it doesn't matter the file had been deleted and re-added since. At the same time, since it's `.epub` I can always see what chapter and page I'm on from the table of contents.  

I suggest testing whether that would be the case for your setup too, your reader may remember the page you were on previously so your progress may stay. As to remembering where you were in terms of chapter, you can always see the last chapter before you update a manga from the program itself, and every manga I've seen (so far) has had the chapter number on the first page of said chapter, but I can absolutely see how that's awkward to find again if you're looking for a page number through thousands of pages, kinda requiring you to math it out or just randomly jump through progress. I guess as a last ditch effort you can keep a note or metadata with the page number you left off at, but that's.. not ideal, to put it very nicely.  

Ultimately I think this is something I'm not going to try to implement, because of two reasons. The logistics would be quite weird (mainly recognizing multiple files as one manga and any sort of standardization of how to do that); and `.cbz` is not the main target format exactly because of issues like the ones you listed alongside the lack of metadata (or rather it not being standardized properly).  

Thank you again for explaining, and I hope this is not a deal breaker for you. This is what turned me away from every other downloader, that they put chapters separately and I had to merge them myself in Calibre to get one complete manga, which was super tedious especially when updating them, so this "design choice" is one of the main reasons for the downloader existing. That's not to say it can't evolve past that, originally it had no downloader at all, and more choice is always better, but yeah at this time I won't implement this.  
I'm glad you're happy with the rest of the program though, and I hope you'll continue to enjoy it!

**Comment by logan17111** [comment]
I use cbz because I used an old wacky program and got used to it.
I use epub too for LN for reading tablet, so I know file format isn't the main issue for me

I will try later when I find something big and still releasing I wanna read and try going for epub + one files to see how it works
I'm not familiar with programming, so I believe you when you say it would be weird lol
Thanks for the answers !
