### ISSUE TITLE
Poor Poor Lips auto pick scanlation problem.

### ISSUE THREAD

**Issue by Moondrag** [ErisLoona/Manga-Library-Manager#2]
When attempting to download the manga mentioned in the title, it starts with a scanlation group but then goes into the other English group since the former didn't do two chapters and stays with them (Even after the latter becomes the only group to do the translation...until the end of Volume 3 when another scanlation group picks up for the rest of the series) even though it should favor the one that did the most for the manga correct? Guessing once the single chapter showed up, it prioritize only that group but not before.

**Comment by ErisLoona** [comment]
The program favors the group who did most of the scanlations *up to that point*, not who translated most of the entire manga, avoiding anonymous scanlations when possible. The program picks the first chapter as given by the API, here though since the two groups scanlate a bunch of chapters from the start it always chooses the first chapter as given by the API between the two.  

So while it works as it should, I can see how this is less than ideal. I'll add an option that will allow choosing between preferring most of the manga and most up to that point.

**Comment by ErisLoona** [comment]
Deployed in [v2.3](https://github.com/ErisLoona/Manga-Library-Manager/releases/tag/v2.3). If you encounter any issues with it let me know.  
Thank you for using my program, hope you enjoy ^-^
