### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by FabianoJanisch** [ErisLoona/Manga-Library-Manager#5]
crashing any manga when put the link in "Add manga from link" with settings selected preffered language "Portuguese" and default settings v3.0

**Comment by ErisLoona** [comment]
Heyo! Can you please [re-download the program](https://github.com/ErisLoona/Manga-Library-Manager/releases) and try again?  

If it still crashes, please provide the manga link that you were trying to add.

**Comment by FabianoJanisch** [comment]
https://www.youtube.com/watch?v=m6_opBC1Z68

**Comment by ErisLoona** [comment]
Thanks for the video, that was very helpful ^-^  
I was able to replicate the crash and am working on it, it's caused by trying to add a manga with no chapters.  

This is because neither of the two mangas have chapters translated in _Portuguese_. They both have chapters translated in "Brazilian Portuguese", near the bottom of the language list. MangaDex makes this distinction and the program follows [their indications on special languages](https://api.mangadex.org/docs/3-enumerations/#language-codes--localization), so you can select _Brazilian Portuguese_ and you should be able to download those mangas just fine.

**Comment by ErisLoona** [comment]
Deployed in [v3.0.1](https://github.com/ErisLoona/Manga-Library-Manager/releases/tag/v3.0.1). Please keep in mind in your case to select the language Brazilian Portuguese to see the chapters. If you encounter any further issues with it please let me know.  

Thank you for using my program, hope you enjoy ^-^
